Repository Jacksx20/JavaWeb_OnlineShopping, pull requests merged in 2024-03, with the labels that each got.

#13 Update README.md
  README.md
Labels: documentation

#14 Update README.md
  README.md
Labels: documentation

#16 Revert "Revert "Update README.md""
  README.md
Labels: bug

#18 Update ManagerFilter
  Shopping/src/java/controller/ManagerFilter.java
Labels: enhancement
